ansible_host: ENC[AES256_GCM,data:4CPy6UUg4zseCiPcIw==,iv:9N+LGwhcT3Ywtotp45KMu2MZerQNdRTAdlMNggeSMEg=,tag:l5qmoxBiGfJzCt2OVp3bTA==,type:str]
ansible_user: ENC[AES256_GCM,data:pbsMug==,iv:CsZUDAODlj7IMuwygL22wjfyEhncrJWbK55xxR+t3Dk=,tag:3mtz3SfpwmE8yNXtu6NjFA==,type:str]
wireguard_ipv6_prefix: ENC[AES256_GCM,data:2cDcgXGoTsCdsMk/DkdUkLjy1hyNFySawhGe,iv:iT+UPGakdm/Q/s6w2eXH2llUHF3RKEosoFBRWjZYjMI=,tag:Dpvq6ZCDYBxLF/pJKRYzag==,type:str]
wireguard_udm_endpoint: ENC[AES256_GCM,data:Zkc8oPjCpQu/ZcS1YPuYhdf/O8m/Ow==,iv:CR3nEWiv2HJqU7JStSZ22xosqdJHPRHCLYkhestm8SQ=,tag:9QCnRepatvWfzaCmD7J/0w==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaC9odmpydDBVVzlwbXl0
            d3NPRjVKcnVyVFNqODNKUC92Y0JxOVBGZ1VBCkREL1lQMHc1clFkK1NPWDlkMXhG
            WWpXWHlWeSs3R1NOYk4vOXhKTXNaeEEKLS0tIFUwSzErMG5HdkdCM1g2N1RCSDl6
            cFBTZWlEbVJuK2gwdXZiMDN2UWw0WW8KODWOCkssAqQ+rcibVH0zSbSiXxQ/o3dB
            xJZD1+TB/Qn9GbqLDLrieLKlqPeGKZcxwg+e2ASYonQX/Hv3eMN4Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T19:29:05Z"
    mac: ENC[AES256_GCM,data:eOeNanV98sEtpF5a1/kbCSEbOM7+vDvxeDU0NE1jaOcIQsOD91vSGVTFha7Jvv0cgMeVypmOxQ2IUWLxjO8H/OSukHeDW0SFP68aLGW38MboN7l+5OuWDMpVw5NMAbJK4ufy5NHDe3FcyXs5mWc5bz3Vx4pyrWMwMYIMZaQJg1k=,iv:Hys9hTOOcy6GntfZZXy4rWX712a2hGiRkT154HJw7pY=,tag:ji7lFumPZJfn70eSswh3mw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
