ansible_host: ENC[AES256_GCM,data:4CPy6UUg4zseCiPcIw==,iv:9N+LGwhcT3Ywtotp45KMu2MZerQNdRTAdlMNggeSMEg=,tag:l5qmoxBiGfJzCt2OVp3bTA==,type:str]
ansible_user: ENC[AES256_GCM,data:pbsMug==,iv:CsZUDAODlj7IMuwygL22wjfyEhncrJWbK55xxR+t3Dk=,tag:3mtz3SfpwmE8yNXtu6NjFA==,type:str]
wireguard_ipv6_prefix: ENC[AES256_GCM,data:2cDcgXGoTsCdsMk/DkdUkLjy1hyNFySawhGe,iv:iT+UPGakdm/Q/s6w2eXH2llUHF3RKEosoFBRWjZYjMI=,tag:Dpvq6ZCDYBxLF/pJKRYzag==,type:str]
wireguard_udm_endpoint: ENC[AES256_GCM,data:anubYP7pY3z+pvJIxE1DQWegIA==,iv:WqylemCWO5a5fopdppbBs3w85Nmsp3eDNhvXyMysTrk=,tag:RzZz/C61df1rE65DIwL1+A==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaC9odmpydDBVVzlwbXl0
            d3NPRjVKcnVyVFNqODNKUC92Y0JxOVBGZ1VBCkREL1lQMHc1clFkK1NPWDlkMXhG
            WWpXWHlWeSs3R1NOYk4vOXhKTXNaeEEKLS0tIFUwSzErMG5HdkdCM1g2N1RCSDl6
            cFBTZWlEbVJuK2gwdXZiMDN2UWw0WW8KODWOCkssAqQ+rcibVH0zSbSiXxQ/o3dB
            xJZD1+TB/Qn9GbqLDLrieLKlqPeGKZcxwg+e2ASYonQX/Hv3eMN4Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T19:24:31Z"
    mac: ENC[AES256_GCM,data:qQkqLLcjYyjCqrFgm6VBxOrBC6tH3XrYF6DMneNgLMSHEX6jbULwy86b/cIScXQoPmAvK33l/+V+xeNo4/cgaK7q/bbnSksfAMAmz/KYkYysQRhDtmxZj62cDXWKLBPNRlZXkAist6V/bo1pqDOQqwF87HzAstLU0jgeAckNg5w=,iv:HiJUdDFigluTL4UN1zO0NlXgvuToc4Ci4wa7dvKmEi0=,tag:4b47QOm88nCVve06WiUH0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
