{
 "title": "Homelab Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last WAN Speedtest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "Upload"
    },
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "WAN Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{instance=\"opnsense.18b.lan:9100\",device=\"igc1\"}[5m]))*8",
     "legendFormat": "Down"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{instance=\"opnsense.18b.lan:9100\",device=\"igc1\"}[5m]))*8",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Tunnels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(count(cloudflared_tunnel_ha_connections), 1)",
     "legendFormat": "Cloudflare Tunnel"
    },
    {
     "expr": "wireguard_latest_handshake_seconds{public_key=\"EdmzcHAwnIn5Uv/SRDKBnwBUZIVxZ2MUnT7Ps/zFLHw=\"} * 1000",
     "legendFormat": "Last Wireguard Handshake"
    }
   ]
  },
  {
   "title": "UniFi Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(unpoller_device_info{type=\"uap\"})",
     "legendFormat": "APs"
    },
    {
     "expr": "count(unpoller_device_info{type=\"usw\"})",
     "legendFormat": "Switches"
    }
   ]
  },
  {
   "title": "UniFi Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(unpoller_client_uptime_seconds{wired=\"true\"} > 0)",
     "legendFormat": "Wired"
    },
    {
     "expr": "count(unpoller_client_uptime_seconds{wired=\"false\"} > 0)",
     "legendFormat": "Wireless"
    }
   ]
  },
  {
   "title": "Proxmox",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(pve_node_info)", "legendFormat": "Nodes" },
    {
     "expr": "count(pve_up == 1 and on(id) pve_guest_info)",
     "legendFormat": "Running VMs"
    },
    {
     "expr": "count(pve_up == 0 and on(id) pve_guest_info)",
     "legendFormat": "Stopped VMs"
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "Nodes" },
    { "expr": "count(kube_namespace_created)", "legendFormat": "Namespaces" },
    { "expr": "count(kube_pod_info)", "legendFormat": "Pods" },
    { "expr": "count(kube_pod_container_info)", "legendFormat": "Containers" }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Traffic: Firewall",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{instance=\"opnsense.18b.lan:9100\"}[5m])*8) by(instance, device))",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{instance=\"opnsense.18b.lan:9100\"}[5m])*8) by(instance, device))",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic: Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(unpoller_device_port_receive_bytes_total{}[5m])*8) by (name, port_id, port_name)",
     "legendFormat": "{{port_name}}  - Receive"
    },
    {
     "expr": "sum(irate(unpoller_device_port_transmit_bytes_total{}[5m])*8) by (name, port_id, port_name)",
     "legendFormat": "{{port_name}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic: Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{instance!=\"opnsense.18b.lan:9100\"}[5m])*8) by(instance)) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}} - Receive"
    },
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{instance!=\"opnsense.18b.lan:9100\"}[5m])*8) by(instance)) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic: APs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(unpoller_device_receive_bytes_total{type=\"uap\"}[5m])*8) by (name)",
     "legendFormat": "{{name}} - Receive"
    },
    {
     "expr": "sum(irate(unpoller_device_transmit_bytes_total{type=\"uap\"}[5m])*8) by (name)",
     "legendFormat": "{{name}} - Transmit"
    }
   ]
  },
  { "title": "Utilization: Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))) * 100) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((((avg_over_time(node_memory_MemTotal_bytes{}[$__rate_interval]) - avg_over_time(node_memory_MemAvailable_bytes{}[$__rate_interval])) / avg_over_time(node_memory_MemTotal_bytes{}[$__rate_interval])) * 100) or (((avg_over_time(node_memory_active_bytes{}[$__rate_interval]) + avg_over_time(node_memory_wired_bytes{}[$__rate_interval])) / avg_over_time(node_memory_size_bytes{}[$__rate_interval])) * 100)) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "System Load (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(node_load5{}[$__rate_interval]) / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{}[$__rate_interval]))) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "System Load (15min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(node_load15{}[$__rate_interval]) / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{}[$__rate_interval]))) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Root Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 - ((avg_over_time(node_filesystem_avail_bytes{mountpoint=\"/\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{mountpoint=\"/\"}[$__rate_interval]))) + on(instance) group_left(nodename) (0* node_uname_info{})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Ulilization: UniFi Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "unpoller_device_cpu_utilization_ratio{}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "unpoller_device_memory_utilization_ratio{}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System Load (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "unpoller_device_load_average_5{}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System Load (15min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "unpoller_device_load_average_15{}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}