{
 "title": "Homelab Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "unifi_device",
    "query": {
     "query": "label_values(unpoller_device_info,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval])))) * 100) + on(instance) group_left(nodename) (0* node_uname_info{instance=~\"$instance\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "System Load (load5)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(node_load5{instance=~\"$instance\"}[$__rate_interval]) / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]))) + on(instance) group_left(nodename) (0* node_uname_info{instance=~\"$instance\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((((avg_over_time(node_memory_MemTotal_bytes{instance=~\"$instance\"}[$__rate_interval]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$instance\"}[$__rate_interval])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$instance\"}[$__rate_interval])) * 100) or (((avg_over_time(node_memory_active_bytes{instance=~\"$instance\"}[$__rate_interval]) + avg_over_time(node_memory_wired_bytes{instance=~\"$instance\"}[$__rate_interval])) / avg_over_time(node_memory_size_bytes{instance=~\"$instance\"}[$__rate_interval])) * 100)) + on(instance) group_left(nodename) (0* node_uname_info{instance=~\"$instance\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m])*8) by(instance)) + on(instance) group_left(nodename) (0* node_uname_info{instance=~\"$instance\"})",
     "legendFormat": "{{nodename}} - Receive"
    },
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{instance=~\"$instance\"}[5m])*8) by(instance)) + on(instance) group_left(nodename) (0* node_uname_info{instance=~\"$instance\"})",
     "legendFormat": "{{nodename}} - Transmit"
    }
   ]
  },
  {
   "title": "Root Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 - ((avg_over_time(node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\"}[$__rate_interval]))) + on(instance) group_left(nodename) (0* node_uname_info{instance=~\"$instance\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "UniFi Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "unpoller_device_cpu_utilization_ratio{name=~\"$unifi_device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System Load (load5)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "unpoller_device_load_average_5{name=~\"$unifi_device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "unpoller_device_memory_utilization_ratio{name=~\"$unifi_device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(unpoller_device_port_receive_bytes_total{name=~\"$unifi_device\"}[5m])) by (name) or sum(rate(unpoller_device_receive_bytes_total{name=~\"$unifi_device\"}[5m])) by (name)",
     "legendFormat": "{{name}} - Receive"
    },
    {
     "expr": "sum(rate(unpoller_device_port_transmit_bytes_total{name=~\"$unifi_device\"}[5m])) by (name) or sum(rate(unpoller_device_transmit_bytes_total{name=~\"$unifi_device\"}[5m])) by (name)",
     "legendFormat": "{{name}} - Transmit"
    }
   ]
  }
 ]
}