apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns
stringData:
    api-key: ENC[AES256_GCM,data:SGL800iM7y9AH8zyk1VjrNI4hAVODhPIIJ089torQw8=,iv:eUlK6N7E3ih2sggGicwlIIph9enzBwCY2S339mhA9m8=,tag:GTgYMHTPuFTvnn9LPqZjBA==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVIrOU9VYStuQm9Xc0tq
            cnNQTFFZdklKTDNFSVN4TWxyUHB3bGJpZkVBCkxEVCt3SGhPZE1vQ0xBemdzS3VB
            Z2RPUUdyRHluWVJ3a1dPRzQwY0IrVkUKLS0tIHhGS3o5MThtV3dXZXlNMGpVcnVj
            NHYwOUYzazFvMjhCUjZaSTd3Y044R1UKm4DMcICyIvEzXc8XaH+Fa5jj70slZi37
            6G+dzVFxErOmt37kM62nSJXfrf1DtSOG+12yzSQN5wS/BfXDb5nzZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:15:38Z"
    mac: ENC[AES256_GCM,data:F2B41iONVS347vuli04Ci0K+nZ2ZCOeMYLaTxIumvrDpW//bEUA1/28wcxG/XVSDzQ1Ibs8HUwLPzrvic7UmYP5DmwMDyF4i5+kQP3oqVy8KBas2BS6rqLUcT8q5cHmuN9uH0RXDwO6vNaaG1xSUVp7EzAODrUmay82rMr9j/lY=,iv:/JoAQwJYu5gAu5klTKIzM4YKQw5YdDCIrAyGbBQP47k=,tag:pgbAhWRXPx4PdZWyOR6aZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
