---
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-init-db
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
          envFrom:
            - secretRef:
                name: forgejo-init-db
