---
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-init-db
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18.6@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
          envFrom:
            - secretRef:
                name: forgejo-init-db
