apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns
stringData:
    host: ENC[AES256_GCM,data:alJd8LplIFkxlYESWtt+fLOP63Ou32c=,iv:kq5YPFM0wvUCfyVxPddmAQ9RDngfOzXfDlujeMr297Y=,tag:dvqMkEjJV7xUnHiWhJ4Wdw==,type:str]
    api-key: ENC[AES256_GCM,data:SGL800iM7y9AH8zyk1VjrNI4hAVODhPIIJ089torQw8=,iv:eUlK6N7E3ih2sggGicwlIIph9enzBwCY2S339mhA9m8=,tag:GTgYMHTPuFTvnn9LPqZjBA==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVIrOU9VYStuQm9Xc0tq
            cnNQTFFZdklKTDNFSVN4TWxyUHB3bGJpZkVBCkxEVCt3SGhPZE1vQ0xBemdzS3VB
            Z2RPUUdyRHluWVJ3a1dPRzQwY0IrVkUKLS0tIHhGS3o5MThtV3dXZXlNMGpVcnVj
            NHYwOUYzazFvMjhCUjZaSTd3Y044R1UKm4DMcICyIvEzXc8XaH+Fa5jj70slZi37
            6G+dzVFxErOmt37kM62nSJXfrf1DtSOG+12yzSQN5wS/BfXDb5nzZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T20:49:39Z"
    mac: ENC[AES256_GCM,data:hWR55bJUww+/B0XSFs+tmtD5rIBdGJ7B7MIrqLgOI/K8X8U6j9cCvSLZ+WYiei+gLKv4Gfilo+tOWrkV2WdrhNHiBTsJCHpLzMvZDmL0YgkQlOasI6bLdkJJ/L2t2WOilxOSYkYpZADQelsZ1dUeodjsiOYoZ4UbTkuUuaRLiRo=,iv:j0S88YSWk7fVZllhxewIWCEWYdQNwaEm60SwU4vysJY=,tag:QH+mSSQ7wKo671CCeuq1eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
