apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns
stringData:
    api-key: ENC[AES256_GCM,data:SGL800iM7y9AH8zyk1VjrNI4hAVODhPIIJ089torQw8=,iv:eUlK6N7E3ih2sggGicwlIIph9enzBwCY2S339mhA9m8=,tag:GTgYMHTPuFTvnn9LPqZjBA==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVIrOU9VYStuQm9Xc0tq
            cnNQTFFZdklKTDNFSVN4TWxyUHB3bGJpZkVBCkxEVCt3SGhPZE1vQ0xBemdzS3VB
            Z2RPUUdyRHluWVJ3a1dPRzQwY0IrVkUKLS0tIHhGS3o5MThtV3dXZXlNMGpVcnVj
            NHYwOUYzazFvMjhCUjZaSTd3Y044R1UKm4DMcICyIvEzXc8XaH+Fa5jj70slZi37
            6G+dzVFxErOmt37kM62nSJXfrf1DtSOG+12yzSQN5wS/BfXDb5nzZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:15:44Z"
    mac: ENC[AES256_GCM,data:y7JOVS48+X0I4ZwOHXRssI4mLUmgYHq6IpPqHc3LggCG/wKVAU7xwq2UJVVvOUpImpz3CnD1CXaB9N/J4HOR9+lkXHGsSVufVuJif15aPH80gTNHkEt+dthCUiIW4CP2/mYoIc2j9wTGxvnHSvG1SJSFq5zhEooJjvDgWItQI9M=,iv:9GI8V5v8Y0bRhsz4jd7GMYT6bZ4g0kf6dsPdhQOAgoA=,tag:UdyOy2VxCaXC9ESN6RmmVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
