ups_admin_user: ENC[AES256_GCM,data:6E5gx+Q=,iv:BpaF0L1tdRjYy89kcw4bWT8ZbnWvtCU2Vat35WZ1hwY=,tag:Z0xv+CO+9kfx4GfgROC9QA==,type:str]
ups_admin_password: ENC[AES256_GCM,data:1Hx738Hfe5M=,iv:SjCTHAcNCqhQApg3RNLrKrlMN5j9v7D1AzgZsk75Po8=,tag:1xle6PUsmbcPgs36TpKvbQ==,type:str]
ups_monitor_user: ENC[AES256_GCM,data:wpN6CDfccQ==,iv:9cnXsvuKStHoH6FF6mu58ewENLGP16Y/hYMm8T5hwKY=,tag:iBEW0ArhjrG8bDceQvOASg==,type:str]
ups_monitor_password: ENC[AES256_GCM,data:oWnropCvBWg=,iv:uG4pSragwl3eEq+3Ag4mOm7ExXdw8nDXuNn2ZDHNpCc=,tag:JcynE7ZVzWtNtYhWPlJRig==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaC9odmpydDBVVzlwbXl0
            d3NPRjVKcnVyVFNqODNKUC92Y0JxOVBGZ1VBCkREL1lQMHc1clFkK1NPWDlkMXhG
            WWpXWHlWeSs3R1NOYk4vOXhKTXNaeEEKLS0tIFUwSzErMG5HdkdCM1g2N1RCSDl6
            cFBTZWlEbVJuK2gwdXZiMDN2UWw0WW8KODWOCkssAqQ+rcibVH0zSbSiXxQ/o3dB
            xJZD1+TB/Qn9GbqLDLrieLKlqPeGKZcxwg+e2ASYonQX/Hv3eMN4Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T21:11:57Z"
    mac: ENC[AES256_GCM,data:FD16qzVcZZpljE58Z6C+hXIPAeqnDjOz4EA9uU4MWcKXHslJE/GgDeGdcvsiS+09G+7JiX7wHILOk5XDbDVqA+4Ar4yasLnUOKSOR/Qu+yKpN4/jiz5V2pngEGx+5Mfkn8qyX7JN9/PrkdrL3VQgHoN2Qy7D1+IZ6UC5qcUZ7Xg=,iv:iual3/IdpJ0hYye+269TS+pYptfdHOclH/nyM4YfXXE=,tag:z2I3WGZCcYMsfpHSBfEcfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
