apiVersion: v1
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:KRDHZj2XvZOji0H/zaFVe428CtDgW87umtQ3yJ9ve42bly1iGvf/u1JLjDHhRui14GSiy95rh4ofySbqodoWLastLUJnnxJPMMxsAdNtlyvk/4UfEs3J7RRYXgo3wxz+jo9SDXuaLOhD84nLjqlow0qeIgnJAeBQGRNtEeGzbal+uiQZOpQq6DrglyqRQtBBhj9teVQgCIptgKU8U1GbtvM8ubr5c2x8mhskSPpw6aKHG62HZ0BTLmBuwQzESchSRSJ3Dn13GL1GMWGQumj4KAwzR+i6fy8fcM0=,iv:BG8Yh9eng1wHmeVbru96HIpJRTiqxpvXeP/5G3EWATA=,tag:H0tA++7bjUutEFxTM7yXnQ==,type:str]
kind: Secret
metadata:
    name: dockerhub-auth
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxekNsQnRQVWdkSWdCNmFE
            V0NwS0dMdVg1QWdsT0IwL05BaFp5UStpNFg0CnhiVjZBUE5PaCtkWGFXRTJNY2pj
            d3REdmxRRDFVK0JxYjIxbkpNd015K1EKLS0tIEpwOE82VFJ2UkhCbzczSWg5Y21x
            Uy9aZ2FBM2E0YkVNVWE2bkpsYUtRUHcKwMkg2gNJ2kkCjudxPGW3BFF2C9qXEw4M
            t99biVKmE+W55bapQiA6HIvR458LGCrYXBbVIMCn4vn6bQRJ9UhDvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T17:27:40Z"
    mac: ENC[AES256_GCM,data:IbakR9L9eBhHCk+lwTivh+TZBQpI+nTDKgQHlVQleWcWHvAT2jFL97s5pXG+tX4mMcAQwr6aO8a5Ghy4on5inWXkVR93QAgYxqEQOAwuFLJ7ik+doHXORI9y4Xd+anOl2bOvQ5GhbAWxmFfetbPTT0t/4Bc5ZDQXTsR/PP/Qo34=,iv:ZCZZYoI0RfnMR8WM9+9L9tjPIFXplt8wa7VsBPHH7QM=,tag:kdhw0B+Cr68OSUI+C6K5Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
