---
name: "Publish Schemas"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main"]
    paths: [".github/workflows/publish-schemas.yaml"]

env:
  DEBCONF_NONINTERACTIVE_SEEN: "true"
  DEBIAN_FRONTEND: noninteractive
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: DontWarn

jobs:
  publish-schemas:
    name: Publish Schemas
    runs-on: ["arc-runner-set-home-ops"]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install kubectl
        uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.14.x

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/kubernetes-schemas
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Python Dependencies
        run: pip install pyyaml

      - name: Setup sops
        uses: nhedger/setup-sops@18e52f363488ed469d2e1855e542a1c651743bba # v3.0.0

      - name: Run crd-extractor
        uses: martinohmann/.github/actions/sops-exec-env@d18813a5931df23768186878cbf89db879a31c43 # main
        with:
          age-key: ${{ secrets.SOPS_AGE_KEY }}
          env-file: .github/secrets/publish-schemas.sops.env
          run: |
            export KUBECONFIG="$(mktemp /tmp/kubeconfig.XXXXX)"
            trap "rm -f $KUBECONFIG" EXIT
            echo -n "$KUBECONFIG_BASE64" | base64 -d > "$KUBECONFIG"
            curl -fsSL https://raw.githubusercontent.com/datreeio/CRDs-catalog/43e4407642d4c37683c88711f37caa6c9c20ca40/Utilities/crd-extractor.sh | bash

      - name: Write Dockerfile
        shell: bash
        run: |
          cat <<EOF > Dockerfile
          FROM docker.io/nginxinc/nginx-unprivileged:latest
          USER root
          RUN rm -rf /usr/share/nginx/html
          COPY --chown=nginx:nginx --chmod=755 . /usr/share/nginx/html
          USER nginx
          EOF

      - name: Build and publish container
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: /home/runner/.datree/crdSchemas
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
